"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { BarChart3, TrendingUp, Calendar, Sparkles, Info, Download, FileText, FileSpreadsheet } from "lucide-react";
import Link from "next/link";
import { useEffect, useState, useMemo } from "react";
import { createClient } from "@/lib/supabase/client";
import { Subject } from "@/lib/types";
import { fetchSubscriptionStatus, SubscriptionStatus } from "@/lib/subscription";
import UpgradeDialog from "@/components/subscription/UpgradeDialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

export default function StatsPage() {
  const [subjects, setSubjects] = useState<Subject[]>([]);
  const [loading, setLoading] = useState(true);
  const [isUpgradeDialogOpen, setIsUpgradeDialogOpen] = useState(false);
  const [subscriptionStatus, setSubscriptionStatus] = useState<SubscriptionStatus | null>(null);
  
  const isProUser = subscriptionStatus?.isProUser ?? false;
  const supabase = useMemo(() => createClient(), []);

  useEffect(() => {
    const loadData = async () => {
      try {
        // Fetch subscription first
        const status = await fetchSubscriptionStatus();
        setSubscriptionStatus(status);
        
        // Then fetch subjects
        const { data: { session } } = await supabase.auth.getSession();
        const user = session?.user;
        
        if (!user) {
          setLoading(false);
          return;
        }

        const { data, error } = await supabase
          .from('subjects')
          .select('*')
          .eq('user_id', user.id)
          .order('created_at', { ascending: false });

        if (error) {
          console.error("Error fetching subjects:", error);
        } else {
          interface DatabaseSubject {
            id: string;
            name: string;
            code?: string;
            type: "Theory" | "Practical" | "Clinical" | "Lab";
            total_hours: number;
            hours_present: number;
            threshold: number;
          }

          // Map database fields (snake_case) to TypeScript interface (camelCase)
          const mappedSubjects: Subject[] = (data || []).map((sub: DatabaseSubject) => ({
            id: sub.id,
            name: sub.name,
            code: sub.code,
            type: sub.type,
            totalHours: sub.total_hours,
            hoursPresent: sub.hours_present,
            threshold: sub.threshold,
            attendancePercentage: sub.total_hours > 0 ? (sub.hours_present / sub.total_hours) * 100 : 0
          }));
          setSubjects(mappedSubjects);
        }
      } catch (error) {
        console.error("Error:", error);
      } finally {
        setLoading(false);
      }
    };
    loadData();
  }, [supabase]);

  const handleExportCSV = () => {
    if (!isProUser) {
      setIsUpgradeDialogOpen(true);
      return;
    }

    const headers = ["Subject", "Code", "Type", "Total Classes", "Attended", "Percentage", "Status"];
    const rows = subjects.map(s => {
      const percentage = s.totalHours > 0 ? (s.hoursPresent / s.totalHours) * 100 : 0;
      const status = percentage < s.threshold ? "At Risk" : "Safe";
      
      // Escape fields for CSV to handle commas and double quotes
      const escapeCsv = (field: string | number | undefined) => {
        if (field === undefined || field === null) return '""';
        const stringField = String(field);
        if (stringField.includes('"') || stringField.includes(',') || stringField.includes('\n')) {
          return `"${stringField.replace(/"/g, '""')}"`;
        }
        return stringField;
      };

      return [
        escapeCsv(s.name),
        escapeCsv(s.code),
        escapeCsv(s.type),
        s.totalHours,
        s.hoursPresent,
        `${percentage.toFixed(1)}%`,
        status
      ].join(",");
    });

    const csvContent = [
      headers.join(","),
      ...rows,
      "",
      `"Report generated by 75 Club - ${new Date().toLocaleDateString()}"`
    ].join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", `attendance_report_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleExportPDF = async () => {
    if (!isProUser) {
      setIsUpgradeDialogOpen(true);
      return;
    }

    try {
      const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
        import("jspdf"),
        import("jspdf-autotable"),
      ]);

      const doc = new jsPDF();

      // Header
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("75 Club", 14, 20);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Attendance Report - ${new Date().toLocaleDateString()}`, 14, 28);
      
      // Stats Summary
      const overallPercentage = subjects.reduce((sum, s) => sum + s.hoursPresent, 0) / Math.max(subjects.reduce((sum, s) => sum + s.totalHours, 0), 1) * 100;
      doc.text(`Overall Attendance: ${overallPercentage.toFixed(1)}%`, 14, 35);
      doc.text(`Total Subjects: ${subjects.length}`, 14, 40);

      // Table
      const tableColumn = ["Subject", "Code", "Type", "Classes", "Attended", "%", "Status"];
      const tableRows = subjects.map(s => {
        const percentage = s.totalHours > 0 ? (s.hoursPresent / s.totalHours) * 100 : 0;
        return [
          s.name,
          s.code || "-",
          s.type,
          s.totalHours,
          s.hoursPresent,
          `${percentage.toFixed(1)}%`,
          percentage < s.threshold ? "At Risk" : "Safe"
        ];
      });

      autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 45,
        theme: 'grid',
        headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] }, // Black header to match theme
        styles: { fontSize: 10 },
      });

      // Footer Watermark
      const pageCount = doc.getNumberOfPages();
      for(let i = 1; i <= pageCount; i++) {
          doc.setPage(i);
          doc.setFontSize(10);
          doc.setTextColor(150);
          doc.text('Generated by 75 Club', 14, doc.internal.pageSize.height - 10);
      }

      doc.save(`attendance_report_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error("Failed to export PDF:", error);
      // Fallback alert if export fails
      alert("Failed to generate PDF. Please try again.");
    }
  };

  if (loading) {
    return (
      <div className="min-h-[80vh] flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-black mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading stats...</p>
        </div>
      </div>
    );
  }

  if (subjects.length === 0) {
    return (
      <div className="min-h-[80vh] flex items-center justify-center p-6">
        <Card className="max-w-md w-full bg-white border-4 border-black rounded-3xl shadow-[12px_12px_0px_0px_rgba(0,0,0,1)]">
          <CardContent className="pt-12 pb-12 text-center space-y-6">
            {/* Icon */}
            <div className="flex justify-center">
              <div className="bg-gray-100 p-6 rounded-full">
                <BarChart3 className="h-16 w-16 text-gray-600" />
              </div>
            </div>

            {/* Title */}
            <div className="space-y-2">
              <h2 className="text-3xl font-display font-black text-black">
                No Data Yet
              </h2>
              <p className="text-gray-600 font-medium text-lg">
                Add subjects to see your attendance analytics and insights
              </p>
            </div>

            {/* Features List */}
            <div className="space-y-3 text-left bg-gray-50 p-4 rounded-xl border-2 border-gray-200">
              <div className="flex items-start gap-3">
                <TrendingUp className="h-5 w-5 text-black mt-0.5" />
                <div>
                  <p className="font-display font-bold">Attendance Trends</p>
                  <p className="text-sm text-gray-600">Track your attendance over time</p>
                </div>
              </div>
              <div className="flex items-start gap-3">
                <BarChart3 className="h-5 w-5 text-black mt-0.5" />
                <div>
                  <p className="font-display font-bold">Subject Comparison</p>
                  <p className="text-sm text-gray-600">Compare attendance across subjects</p>
                </div>
              </div>
              <div className="flex items-start gap-3">
                <Calendar className="h-5 w-5 text-black mt-0.5" />
                <div>
                  <p className="font-display font-bold">Monthly Insights</p>
                  <p className="text-sm text-gray-600">See your attendance patterns</p>
                </div>
              </div>
            </div>

            {/* CTA Button */}
            <Link href="/dashboard">
              <Button size="lg" className="w-full font-display font-bold text-lg bg-black hover:bg-gray-800 text-white rounded-xl border-2 border-black">
                ➕ Add Your First Subject
              </Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Calculate stats
  const totalClasses = subjects.reduce((sum, s) => sum + s.totalHours, 0);
  const totalPresent = subjects.reduce((sum, s) => sum + s.hoursPresent, 0);
  const overallPercentage = totalClasses > 0 ? (totalPresent / totalClasses) * 100 : 0;
  const subjectsAtRisk = subjects.filter(s => {
    const percentage = s.totalHours > 0 ? (s.hoursPresent / s.totalHours) * 100 : 0;
    return percentage < s.threshold;
  }).length;

  // FREE TIER: Show only basic stats
  if (!isProUser) {
    return (
      <div className="p-6 space-y-6">
        <div>
          <h1 className="text-3xl font-display font-black text-black">Statistics</h1>
          <p className="text-gray-600 font-medium">Your basic attendance overview</p>
        </div>

        <div className="bg-blue-50 border-2 border-black rounded-xl p-4 flex items-start md:items-center gap-3">
          <Info className="h-5 w-5 text-black shrink-0 mt-0.5 md:mt-0" />
          <p className="text-sm font-medium text-gray-700">
            <span className="font-bold text-black">Pro Tip: </span> Update your attendance regularly to get accurate bunk suggestions.
          </p>
        </div>

        {/* Basic Stats for Free Users */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card className="bg-white border-4 border-black rounded-2xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
            <CardContent className="p-6">
              <div className="flex items-center justify-between mb-2">
                <p className="text-sm font-bold text-gray-600">Total Classes</p>
                <span className="text-2xl">📚</span>
              </div>
              <p className="text-4xl font-display font-black text-black">{totalClasses}</p>
              <p className="text-xs text-gray-500 mt-1">Conducted so far</p>
            </CardContent>
          </Card>

          <Card className="bg-white border-4 border-black rounded-2xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
            <CardContent className="p-6">
              <div className="flex items-center justify-between mb-2">
                <p className="text-sm font-bold text-gray-600">Overall %</p>
                <span className="text-2xl">✨</span>
              </div>
              <p className="text-4xl font-display font-black text-black">{overallPercentage.toFixed(1)}%</p>
              <p className="text-xs text-gray-500 mt-1">Average Attendance</p>
            </CardContent>
          </Card>
        </div>

        {/* Upgrade Prompt */}
        <Card className="bg-gradient-to-br from-yellow-50 to-orange-50 border-4 border-black rounded-2xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
          <CardContent className="p-8 text-center">
            <Sparkles className="h-12 w-12 mx-auto mb-4 text-orange-600" />
            <h2 className="text-2xl font-display font-black text-black mb-2">Unlock Advanced Analytics</h2>
            <p className="text-gray-700 mb-6 max-w-md mx-auto">
              Upgrade to Pro to see detailed subject breakdowns, attendance trends, risk analysis, and more!
            </p>
            <div className="space-y-2 text-left bg-white/50 p-4 rounded-xl border-2 border-black/20 mb-6 max-w-md mx-auto">
              <div className="flex items-center gap-2">
                <span className="text-green-600">✓</span>
                <span className="text-sm font-medium">Subject-wise breakdown with progress bars</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-green-600">✓</span>
                <span className="text-sm font-medium">Subjects at risk analysis</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-green-600">✓</span>
                <span className="text-sm font-medium">Advanced attendance insights</span>
              </div>
            </div>
            <Button 
              size="lg" 
              onClick={() => setIsUpgradeDialogOpen(true)}
              className="bg-gradient-to-r from-yellow-400 to-orange-500 hover:from-yellow-500 hover:to-orange-600 text-black font-bold rounded-xl border-2 border-black"
            >
              <Sparkles className="mr-2 h-5 w-5" />
              Upgrade to Pro
            </Button>
          </CardContent>
        </Card>

        <UpgradeDialog
          open={isUpgradeDialogOpen}
          onOpenChange={setIsUpgradeDialogOpen}
          feature="Advanced Analytics"
          message="Unlock detailed analytics and insights with Pro!"
        />
      </div>
    );
  }

  // PRO TIER: Show full stats
  return (
    <div className="p-6 space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-display font-black text-black">Statistics</h1>
          <p className="text-gray-600 font-medium">Your attendance analytics and insights</p>
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" className="gap-2 border-2 border-black rounded-xl font-bold bg-white hover:bg-gray-50 text-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] active:translate-y-0.5 active:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] transition-all">
              <Download className="h-4 w-4" />
              Export Data
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-48 rounded-xl border-2 border-black">
            <DropdownMenuItem onClick={handleExportCSV} className="gap-2 cursor-pointer font-medium hover:bg-gray-100 focus:bg-gray-100">
              <FileSpreadsheet className="h-4 w-4" />
              Export as CSV
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleExportPDF} className="gap-2 cursor-pointer font-medium hover:bg-gray-100 focus:bg-gray-100">
              <FileText className="h-4 w-4" />
              Export as PDF
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <div className="bg-blue-50 border-2 border-black rounded-xl p-4 flex items-start md:items-center gap-3">
        <Info className="h-5 w-5 text-black shrink-0 mt-0.5 md:mt-0" />
        <p className="text-sm font-medium text-gray-700">
          <span className="font-bold text-black">Pro Tip: </span> Update your attendance regularly to get accurate bunk suggestions.
        </p>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-white border-4 border-black rounded-2xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] hover:shadow-[12px_12px_0px_0px_rgba(0,0,0,1)] transition-all">
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-bold text-gray-600">Total Classes</p>
              <span className="text-2xl">📚</span>
            </div>
            <p className="text-4xl font-display font-black text-black">{totalClasses}</p>
            <p className="text-xs text-gray-500 mt-1">Conducted so far</p>
          </CardContent>
        </Card>

        <Card className="bg-white border-4 border-black rounded-2xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] hover:shadow-[12px_12px_0px_0px_rgba(0,0,0,1)] transition-all">
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-bold text-gray-600">Overall %</p>
              <span className="text-2xl">✨</span>
            </div>
            <p className="text-4xl font-display font-black text-black">{overallPercentage.toFixed(1)}%</p>
            <p className="text-xs text-gray-500 mt-1">Average Attendance</p>
          </CardContent>
        </Card>

        <Card className="bg-white border-4 border-black rounded-2xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] hover:shadow-[12px_12px_0px_0px_rgba(0,0,0,1)] transition-all">
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-bold text-gray-600">At Risk</p>
              <span className="text-2xl">⚠️</span>
            </div>
            <p className="text-4xl font-display font-black text-black">{subjectsAtRisk}</p>
            <p className="text-xs text-gray-500 mt-1">Need attention ASAP</p>
          </CardContent>
        </Card>

        <Card className="bg-white border-4 border-black rounded-2xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] hover:shadow-[12px_12px_0px_0px_rgba(0,0,0,1)] transition-all">
          <CardContent className="p-6">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-bold text-gray-600">Total Subjects</p>
              <span className="text-2xl">📊</span>
            </div>
            <p className="text-4xl font-display font-black text-black">{subjects.length}</p>
            <p className="text-xs text-gray-500 mt-1">Being tracked</p>
          </CardContent>
        </Card>
      </div>

      {/* Subject Breakdown */}
      <Card className="bg-white border-4 border-black rounded-2xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
        <CardContent className="p-6">
          <h2 className="text-xl font-display font-black text-black mb-4">Subject Breakdown</h2>
          <div className="space-y-3">
            {subjects.map((subject) => {
              const percentage = subject.totalHours > 0 ? (subject.hoursPresent / subject.totalHours) * 100 : 0;
              const isAtRisk = percentage < subject.threshold;
              
              return (
                <div key={subject.id} className="border-2 border-gray-200 rounded-xl p-4 hover:border-black transition-colors">
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex-1">
                      <p className="font-display font-bold text-black">{subject.name}</p>
                      <p className="text-xs text-gray-500">{subject.code} • {subject.type}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-2xl font-display font-black text-black">{percentage.toFixed(0)}%</p>
                      <p className="text-xs text-gray-500">{subject.hoursPresent}/{subject.totalHours} classes</p>
                    </div>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div 
                      className={`h-2 rounded-full ${isAtRisk ? 'bg-red-500' : 'bg-black'}`}
                      style={{ width: `${Math.min(percentage, 100)}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
